name: read_assistant
description: "A Read Assistant."
publish_to: 'none'

version: 1.0.5+5

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.1
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.12

flutter:
  uses-material-design: true

# Add this section for MSIX configuration
msix_config:
  display_name: 摸鱼助手
  publisher_display_name: MicoEdu
  identity_name: com.micro.assistant
  logo_path: windows/runner/resources/app_icon.ico
