name: Build All Platforms - Parallel

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps: &flutter-steps
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.35.6' }
      - run: flutter pub get
      - run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with: { name: web-build, path: build/web/ }

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.35.6' }
      - run: flutter pub get
      - run: flutter build windows --release
      - run: |
          $appName = (Get-Content pubspec.yaml | Select-String '^name:' | ForEach-Object { $_.Line.Split(':')[1].Trim() })
          Compress-Archive -Path "build\windows\runner\Release\*" -DestinationPath "$appName-windows.zip"
      - uses: actions/upload-artifact@v4
        with: { name: windows-build, path: "*.zip" }

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.35.6' }
      - run: |
          flutter pub get
          sudo apt-get update && sudo apt-get install -y libgtk-3-dev
      - run: flutter build linux --release
      - run: |
          appName=$(grep '^name:' pubspec.yaml | awk '{print $2}')
          tar -czf $appName-linux.tar.gz -C build/linux/x64/release/bundle/ .
      - uses: actions/upload-artifact@v4
        with: { name: linux-build, path: "*.tar.gz" }

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.35.6' }
      - run: flutter pub get
      - run: flutter build macos --release
      - run: |
          appName=$(grep '^name:' pubspec.yaml | awk '{print $2}')
          cd build/macos/Build/Products/Release/
          zip -r ../../../../$appName-macos.zip $appName.app
      - uses: actions/upload-artifact@v4
        with: { name: macos-build, path: "*-macos.zip" }

  release:
    runs-on: ubuntu-latest
    needs: [build-web, build-windows, build-linux, build-macos]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v4
        with: { path: dist }
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
          generate_release_notes: true